// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCezs3Wo5uCZ76dw0QYvw4Lm50k229wYaY',
    appId: '1:720045304676:web:b3ef54a79b814e14d5e871',
    messagingSenderId: '720045304676',
    projectId: 'kaado-a98bf',
    authDomain: 'kaado-a98bf.firebaseapp.com',
    storageBucket: 'kaado-a98bf.firebasestorage.app',
    measurementId: 'G-1S2P1YCY2P',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vd53xVIcjekmO13pOMSxqiWKXg4pXPA',
    appId: '1:134812932196:android:e108d67afbc61f545d2771',
    messagingSenderId: '134812932196',
    projectId: 'kaado-b7fdb',
    storageBucket: 'kaado-b7fdb.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisunrSuIrQvzf6uUVknAK5jxf_YGLMxw',
    appId: '1:720045304676:ios:fe618b1e709c2e37d5e871',
    messagingSenderId: '720045304676',
    projectId: 'kaado-a98bf',
    storageBucket: 'kaado-a98bf.firebasestorage.app',
    iosBundleId: 'com.claytontechnologies.kaado',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCezs3Wo5uCZ76dw0QYvw4Lm50k229wYaY',
    appId: '1:720045304676:web:2adaa84219cbdecad5e871',
    messagingSenderId: '720045304676',
    projectId: 'kaado-a98bf',
    authDomain: 'kaado-a98bf.firebaseapp.com',
    storageBucket: 'kaado-a98bf.firebasestorage.app',
    measurementId: 'G-FGFPMQM80E',
  );
}
